config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  scope module: :web do
    root to: 'home#index'

    resource :sessions, only: [:new, :create, :destroy]
    resource :registrations, only: [:new, :create]
    resources :teams, only: [:index, :show] do
      scope module: :teams do
        resources :channels, only: [:index, :show, :new, :create]
        resource :join, only: [:create]
      end
    end

    resources :channels, only: [] do
      scope module: :channels do
        resource :join, only: [:create]
      end
    end

    namespace :account do
      resources :teams, only: [:index, :new, :create]
      resources :notifications
      resource :users, only: [:edit, :update, :destroy, :show]
    end
  end

  scope module: :api do
    resources :channels, only: [] do
      scope module: :channels do
        resources :messages, only: [:create, :update, :destroy]
      end
    end
  end
end

app/views/layouts/shared/_head.html.slim
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
  meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
  title Todo
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "application", media: "all"
  / = stylesheet_pack_tag 'application', media: 'all'

app/views/layouts/shared/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light.flex-shrink-0
  a.navbar-brand(href="/") SlackClone
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.ml-auto
      - if signed_in?
        = nav_menu_item t('.notifications'), account_notifications_path
        = nav_menu_item t('.my_teams'), account_teams_path
        = nav_menu_item t('.teams'), teams_path
        li.nav-item.dropdown
          = image_tag user_avatar(current_user), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false
          .dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdown"
            = link_to 'Settings', edit_account_users_path, class: 'dropdown-item'
            = link_to 'Sign out', sessions_path, method: :delete, class: 'dropdown-item'
      - else
        = nav_menu_item t('.sign_in'), new_sessions_path
        = nav_menu_item t('.register'), new_registrations_path